#No se usa docker-compose para este proyecto, pero se deja este archivo como referencia para futuras implementaciones
#services:
 # backend:
    #build: .
    #ports:
     # - "8080:8080"
    #environment:
     # SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/react_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: 12345678
